# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel7"
   config.vm.network "private_network", ip: "192.168.56.111"
   config.vm.network "public_network"
   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "2048"
   end
end
