# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
#  config.hostmanager.enabled = true
#  config.hostmanager.manage_guest = true
#  config.hostmanager.manage_host = true
#  config.vm.provision "shell", path: "bootstrap.sh"


  MasterCount = 1

  # Kubernetes Master Nodes
  (1..MasterCount).each do |i|
    config.vm.define "kmaster" do |masternode|
      masternode.vm.box = "bento/ubuntu-20.04"
      masternode.vm.hostname = "k8smaster.example.com"
      masternode.vm.network "private_network", ip: "192.168.56.100"
      masternode.vm.network "public_network"
      masternode.vm.provider "virtualbox" do |v|
        v.name = "kmaster"
        v.memory = 8192
        v.cpus = 2
      end
    end
  end

  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "kworker#{i}" do |workernode|
      workernode.vm.box = "bento/ubuntu-20.04"
      workernode.vm.hostname = "kworker#{i}.example.com"
      workernode.vm.network "private_network", ip: "192.168.56.10#{i}"
      workernode.vm.network "public_network"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "kworker#{i}"
        v.memory = 4096
        v.cpus = 2
      end

  end

  config.vm.define "jenkinsmaster" do |jenkins|
    jenkins.vm.box = "bento/ubuntu-20.04"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.56.20"
    jenkins.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end
  end


  config.vm.define "jenkinsslave" do |jenkins|
    jenkins.vm.box = "bento/ubuntu-20.04"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.56.21"
    jenkins.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "eurolinux-vagrant/centos-stream-9"
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "192.168.56.23"
    ansible.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end
  end
  config.vm.define "docker" do |docker|
#    docker.vm.box = "roboxes/fedora35"
    docker.vm.box = "centos/7"
    docker.vm.hostname = "docker"
    docker.vm.network "private_network", ip: "192.168.56.24"
    docker.vm.provider "virtualbox" do |vb|
      vb.memory="2048"
    end
  end
  config.vm.define "tomcat" do |tomcat|
    tomcat.vm.box = "eurolinux-vagrant/centos-stream-9"
    tomcat.vm.hostname = "tomcat"
    tomcat.vm.network "private_network", ip: "192.168.56.25"
    tomcat.vm.provider "virtualbox" do |vb|
      vb.memory="2048"
    end
  end

  config.vm.define "sonarqube" do |sonarqube|
  config.vm.provision "shell", path: "/home/vsk/DEVOPS-DATACENTER/codes-shell/ubuntu20-sonar-setup.sh"
    sonarqube.vm.box = "bento/ubuntu-20.04"
    sonarqube.vm.hostname = "jenkins"
    sonarqube.vm.network "private_network", ip: "192.168.56.26"
    sonarqube.vm.provider "virtualbox" do |vb|
     vb.memory = "6048"
   end
  end

  config.vm.define "nexus" do |nexus|
  config.vm.provision "shell", path: "/home/vsk/DEVOPS-DATACENTER/codes-shell/centos-nexus-setup.sh"
    nexus.vm.box = "centos/7"
    nexus.vm.hostname = "nexus"
    nexus.vm.network "private_network", ip: "192.168.56.27"
    nexus.vm.provider "virtualbox" do |vb|
     vb.memory = "3048"
   end
  end





 end

end
